### ISSUE TITLE
Do not invalidate input if value is null

### ISSUE THREAD

**Issue by rosostolato** [yannickebongue/ngx-material-time-select#1]
On my tests, I'm getting `ng-invalid` if the input is empty and no matter what my angular `FormBuilder` says about its validation.

Should exist an option to do not invalidate empty value (or maybe it exists and I didn't find).

**EDIT**

With more tests I found that it starts invalid, but if you try to update any value and erase it back, it removes the ng-invalid

**EDIT 2**

And this is the error that it throws
`{matTimeSelectParse: {text: ""}}`

**Comment by yannickebongue** [comment]
Hi @rosostolato 

I tried to reproduce the issue with the latest version but I was not able to get the parse error with an empty input value.

Can you please give more details about your test case?

Remember that the current version of the `ngx-material-time-select` library requires the following dependencies:
- "@angular/core": "~7.2.3"
- "@angular/material": "^7.3.0"

Best regards,

@yannickebongue

**Comment by rosostolato** [comment]
Thanks for your answer!

I confess that I'm on version 0.1 because I'm getting injection fail on `DateAdapter` with the lastest version and as v0.1 was working for me as I want, I continued using this version.

I could create an app to reproduce the error with v0.1 or I can try again with lastest version. What do you think?

I'm using:
* "@angular/core": "~7.2.4"
* "@angular/material": "^7.3.1"

**Comment by yannickebongue** [comment]
I recommend to use the latest version (v0.2.1) which already fits with your Angular Core and Angular Material dependencies.

**Comment by rosostolato** [comment]
Ok, I'll try to update and test again.

Em qua, 27 de fev de 2019 11:49, Yannick Ebongue <notifications@github.com>
escreveu:
