### ISSUE TITLE
@angular/material/material"' has no exported member 'CanColorCtor'.

### ISSUE THREAD

**Issue by faridaanjum** [yannickebongue/ngx-material-time-select#3]
ERROR in node_modules/ngx-material-time-select/lib/time-select.component.d.ts(4,20): error TS2305: Module '"C:/Users/Farida/git/ppms-4-12/ppms-root/app/ppms-ui/ui/node_modules/@angular/material/material"' has no exported member 'CanColorCtor'.
node_modules/ngx-material-time-select/lib/time-select.component.d.ts(53,22): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ngx-material-time-select/lib/time-unit-option.component.d.ts(2,10): error TS2305: Module '"C:/Users/Farida/git/ppms-4-12/ppms-root/app/ppms-ui/ui/node_modules/@angular/material/material"' has no exported member 'CanDisableRippleCtor'.
node_modules/ngx-material-time-select/lib/time-unit-option.component.d.ts(21,22): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ngx-material-time-select/lib/time-unit-option.component.d.ts(23,21): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ngx-material-time-select/lib/time-unit-option.component.d.ts(25,25): error TS1039: Initializers are not allowed in ambient contexts.

These errors are coming while integrating Time Select.

I am using material   "@angular/material": "^6.3.0",  with angular6.

Please Can you help me in this.

**Comment by yannickebongue** [comment]
You just have to upgrade your Angular version.

Here below the package dependencies you need to check:

- `@angular/core: ~7.2.3`
- `@angular/material: ^7.3.0`

**Comment by faridaanjum** [comment]
Can't I use this with angular6

**Comment by yannickebongue** [comment]
Unfortunately no. The component is built on top of Angular Material 7.3 and requires Angular 7

**Comment by faridaanjum** [comment]
Ok. Thank you very much for your reply
